version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Selim123
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  jd-ticketing:
    image: jd-ticketing
    restart: always
    ports:
      - 808:8080
    depends_on:
      - db
volumes:
  database-data: {}
